version: '3.4'

services:
  ms-sql-server:
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "MyP@sswordSQL"
    container_name: sqlserver
    ports:
      - "1433:1433"    
    volumes:
      - ./sqlserver-data:/var/opt/mssql/data
    restart: always
  authmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44317:80"
      - "44318:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  #website:
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
  #  ports:
  #    - "5173:5173"
  #  container_name: website